//
//  LSIFirstResponder.m
//  Quakes-Objc
//
//  Created by Audrey Welch on 5/4/20.
//  Copyright © 2020 Lambda, Inc. All rights reserved.
//

#import "LSIFirstResponder.h"

@implementation LSIFirstResponder

- (instancetype)initWithName:(NSString *)name
                    usingAge:(int)age {
    self = [super init];
    if (self) {
        
        // NSMutableString -> NSString (constant)
        // Rule: When initializing NSString, you should also use copy
        _name = [name copy]; // protects from NSMutableString being stored
        _age = age;
    }
    return self;
}

// 3. Create the instance variable
// Tell the compiler we do want the autogenerated variable
// @synthesize nameOfProperty = _nameOfInstanceVariable
@synthesize name = _name;

// Setter
- (void)setName:(NSString *)name {
    // willSet

    _name = [name copy];

    // didSet
    // [self updateViews];
}

// Getter
- (NSString *)name {
    return _name;
}

@end
